/* The logo, inlined.
 *
 * Inline rather than <img src="…svg"> because currentColor does not
 * resolve inside an SVG loaded as an image — it silently renders black.
 * Inlining is what lets the mark inherit text colour, so the nav, the
 * footer and the OG card all use one component at different colours.
 *
 * Paths are duplicated from public/logo/ajwc-mark.svg, which is
 * generated by scripts/build-logo.py. If the mark changes, re-run that
 * script and paste the new paths here.
 */

export function Mark({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 64 64"
      fill="currentColor"
      className={className}
      role="img"
      aria-label="AJWC Tech Consulting"
    >
      <path
        fillRule="evenodd"
        d="M32.00 2.00 6.02 17.00 6.02 47.00 32.00 62.00 57.98 47.00 57.98 17.00Z M32.00 8.00 11.22 20.00 11.22 44.00 32.00 56.00 52.78 44.00 52.78 20.00Z"
      />
      <g fillOpacity="0.6">
        <path d="M30.17 11.08 14.80 19.95 21.26 27.88 28.26 21.13Z" />
        <path d="M12.97 23.13 12.97 40.87 23.06 39.24 20.71 29.81Z" />
        <path d="M14.80 44.05 30.17 52.92 33.80 43.36 24.46 40.68Z" />
        <path d="M33.83 52.92 49.20 44.05 42.74 36.12 35.74 42.87Z" />
        <path d="M51.03 40.87 51.03 23.13 40.94 24.76 43.29 34.19Z" />
        <path d="M49.20 19.95 33.83 11.08 30.20 20.64 39.54 23.32Z" />
      </g>
    </svg>
  );
}
